# Docker Compose Override para EasyPanel
# Este arquivo garante que o build funcione corretamente no ambiente de deploy

version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: nextkanban-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nextkanban
      POSTGRES_USER: nextkanban_user
      POSTGRES_PASSWORD: nextkanban_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nextkanban_user -d nextkanban"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nextkanban-network

  nextkanban:
    build:
      context: ..
      dockerfile: ../Dockerfile
      args:
        DATABASE_URL: postgresql://nextkanban_user:nextkanban_password@postgres:5432/nextkanban
        DB_HOST: postgres
        DB_PORT: 5432
        DB_NAME: nextkanban
        DB_USER: nextkanban_user
        DB_PASSWORD: nextkanban_password
        NEXTAUTH_SECRET: your-secret-key-here-change-in-production
        NEXTAUTH_URL: http://localhost:48321
        JWT_SECRET: your-jwt-secret-here-change-in-production
    container_name: nextkanban-app
    restart: unless-stopped
    ports:
      - "48321:48321"
    environment:
      - DATABASE_URL=postgresql://nextkanban_user:nextkanban_password@postgres:5432/nextkanban
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=nextkanban
      - DB_USER=nextkanban_user
      - DB_PASSWORD=nextkanban_password
      - NEXTAUTH_SECRET=your-secret-key-here-change-in-production
      - NEXTAUTH_URL=http://localhost:48321
      - JWT_SECRET=your-jwt-secret-here-change-in-production
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nextkanban-network

volumes:
  postgres_data:
    driver: local

networks:
  nextkanban-network:
    driver: bridge
