# Docker Compose Override para EasyPanel
# Este arquivo garante que o build funcione corretamente no ambiente de deploy

services:
  nextkanban:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DATABASE_URL: postgresql://nextkanban_user:nextkanban_password@postgres:5432/nextkanban
        DB_HOST: postgres
        DB_PORT: 5432
        DB_NAME: nextkanban
        DB_USER: nextkanban_user
        DB_PASSWORD: nextkanban_password
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-your-secret-key-here-change-in-production}
        NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:48321}
        JWT_SECRET: ${JWT_SECRET:-your-jwt-secret-here-change-in-production}
        GIT_SHA: ${GIT_SHA:-latest}
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://nextkanban_user:nextkanban_password@postgres:5432/nextkanban
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=nextkanban
      - DB_USER=nextkanban_user
      - DB_PASSWORD=nextkanban_password
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-secret-key-here-change-in-production}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:48321}
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-here-change-in-production}